export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const SET_INGREDIENTS_STATE = "SET_INGREDIENTS_STATE";
export const HANDLE_CHECKOUT = "HANDLE_CHECKOUT";
export const ORDER_PROCESSING = "ORDER_PROCESSING";
export const PLACE_ORDER = "PLACE_ORDER";
export const CANCEL_CHECKOUT = "CANCEL_CHECKOUT";
export const LOGIN_PLACE_ORDER = "LOGIN_PLACE_ORDER";
